### ISSUE TITLE
Can't clone repo

### ISSUE THREAD

**Issue by AlbertoBoem** [CIMIL/SpatialAudioWebXR#2]
Se cerco di clonare la repo, ricevo questo errore:

remote: Enumerating objects: 167, done.        
remote: Counting objects: 100% (167/167), done.        
remote: Compressing objects: 100% (119/119), done.        
remote: Total 167 (delta 52), reused 145 (delta 34), pack-reused 0        
Receiving objects: 100% (167/167), 3.97 MiB | 4.56 MiB/s, done.
Resolving deltas: 100% (52/52), done.
error: invalid path 'PannerNode/dist/audio/crowd.mp3:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by Samu01Tech** [comment]
Questo è temporaneo, appena tolgo tutte le cartelle vecchie dovrebbe sparire questo errore

**Comment by AlbertoBoem** [comment]
Stesso errore di prima:

Cloning into 'C:\Users\boema\Develop\Github_projects\SpatialAudioWebXR'...
remote: Enumerating objects: 167, done.        
remote: Counting objects: 100% (167/167), done.        
remote: Compressing objects: 100% (119/119), done.        
remote: Total 167 (delta 52), reused 145 (delta 34), pack-reused 0        
Receiving objects: 100% (167/167), 3.97 MiB | 28.21 MiB/s, done.
Resolving deltas: 100% (52/52), done.
error: invalid path 'PannerNode/dist/audio/crowd.mp3:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by AlbertoBoem** [comment]
Mi sono accorto che era ancora il (classico) problema di path troppo lunghi. A Windows non piaccono. 
Ho risolto cosi:

- installa git LFS
- git config --system core.longpaths true
- git config --global core.protectNTFS false

**Comment by AlbertoBoem** [comment]
La considero chiusa
