### ISSUE TITLE
AframeresonanceAudioComponent (Meta Quest Browser, Wolvic) : can't use "back" button

### ISSUE THREAD

**Issue by AlbertoBoem** [CIMIL/SpatialAudioWebXR#4]
Non posso utilizzare il pulsante "back"

**Comment by Samu01Tech** [comment]
Si ogni volta quando copio i componenti di camera e controlli mi perdo qualcosa. Sistemerò

**Comment by AlbertoBoem** [comment]
Ok, quando hai sistemato chiudi la issue
