### ISSUE TITLE
Pannernode + AframeresonanceAudioComponent (Meta Quest Browser, Wolvic): audio sample not working

### ISSUE THREAD

**Issue by AlbertoBoem** [CIMIL/SpatialAudioWebXR#5]
In tutti gli esempi, su tutti i browser, il sample audio sembra che sia messo in loop. 
Questo non va bene.
Deve essere mandato in play una sola volta, oppure inserire una funzione che lo faccia ripetere ad intervalli regolari ma con del silenzio.
Fatto cosi come e' adesso non ha senso.

**Comment by Samu01Tech** [comment]
Ok, questo si modifica facilmente

**Comment by AlbertoBoem** [comment]
Quando lo hai modificato, chiudi la issue

**Comment by Samu01Tech** [comment]
È adesso possibile impostare un intervallo a piacere tramite il file `constants.js` in millisecondi #8
