### ISSUE TITLE
Meta Quest Browser + Wolvic : the application is slow and not constant

### ISSUE THREAD

**Issue by AlbertoBoem** [CIMIL/SpatialAudioWebXR#6]
L'applicazione in tutti e due i browser e' scostante e molto lenta.
Non sono sicuro poi che sia veramente in tempo reale.
Sembra che ci sia un lag soprattutto in Resonance.
Come mai?

**Comment by AlbertoBoem** [comment]
Meta Quest Browser: https://drive.google.com/file/d/1--z1_RfNCSxaqVN5fX0Y41l-LvuGYvIf/view?usp=sharing
Wolvic: https://drive.google.com/file/d/1DQhHrEmZLHNmkuSuGRzdre2_zv0ibxuw/view?usp=sharing

Nei video i lag e i problemi di fludita' sono molto meno evidenti.
A te, con il visore Quest, non succede?

**Comment by Samu01Tech** [comment]
Mmm strano, sinceramente non ho notato lag se non dopo il click per entrare in una delle esperienze però quello è normale perché è un altra pagina html. Ricontrollerò

**Comment by AlbertoBoem** [comment]
Ok grazie.

**Comment by Samu01Tech** [comment]
Effettivamente il rallentamento avveniva dopo un po' a causa di un memory leak. È stato risolto nella #8
